
package fi.jyu.pservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ComputeAreaImplService", targetNamespace = "http://pservice.jyu.fi/", wsdlLocation = "http://localhost:8080/jyuService/pservice?wsdl")
public class ComputeAreaImplService
    extends Service
{

    private final static URL COMPUTEAREAIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException COMPUTEAREAIMPLSERVICE_EXCEPTION;
    private final static QName COMPUTEAREAIMPLSERVICE_QNAME = new QName("http://pservice.jyu.fi/", "ComputeAreaImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/jyuService/pservice?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        COMPUTEAREAIMPLSERVICE_WSDL_LOCATION = url;
        COMPUTEAREAIMPLSERVICE_EXCEPTION = e;
    }

    public ComputeAreaImplService() {
        super(__getWsdlLocation(), COMPUTEAREAIMPLSERVICE_QNAME);
    }

    public ComputeAreaImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), COMPUTEAREAIMPLSERVICE_QNAME, features);
    }

    public ComputeAreaImplService(URL wsdlLocation) {
        super(wsdlLocation, COMPUTEAREAIMPLSERVICE_QNAME);
    }

    public ComputeAreaImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, COMPUTEAREAIMPLSERVICE_QNAME, features);
    }

    public ComputeAreaImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ComputeAreaImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ComputeAreaImpl
     */
    @WebEndpoint(name = "ComputeAreaImplPort")
    public ComputeAreaImpl getComputeAreaImplPort() {
        return super.getPort(new QName("http://pservice.jyu.fi/", "ComputeAreaImplPort"), ComputeAreaImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ComputeAreaImpl
     */
    @WebEndpoint(name = "ComputeAreaImplPort")
    public ComputeAreaImpl getComputeAreaImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://pservice.jyu.fi/", "ComputeAreaImplPort"), ComputeAreaImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (COMPUTEAREAIMPLSERVICE_EXCEPTION!= null) {
            throw COMPUTEAREAIMPLSERVICE_EXCEPTION;
        }
        return COMPUTEAREAIMPLSERVICE_WSDL_LOCATION;
    }

}
