
package fi.jyu.pservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ComputeAreaImpl", targetNamespace = "http://pservice.jyu.fi/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ComputeAreaImpl {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ComputeTriangleAreaByBaseAndHeight")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ComputeTriangleAreaByBaseAndHeight", targetNamespace = "http://pservice.jyu.fi/", className = "fi.jyu.pservice.ComputeTriangleAreaByBaseAndHeight")
    @ResponseWrapper(localName = "ComputeTriangleAreaByBaseAndHeightResponse", targetNamespace = "http://pservice.jyu.fi/", className = "fi.jyu.pservice.ComputeTriangleAreaByBaseAndHeightResponse")
    @Action(input = "http://pservice.jyu.fi/ComputeAreaImpl/ComputeTriangleAreaByBaseAndHeightRequest", output = "http://pservice.jyu.fi/ComputeAreaImpl/ComputeTriangleAreaByBaseAndHeightResponse")
    public String computeTriangleAreaByBaseAndHeight(
        @WebParam(name = "arg0", targetNamespace = "")
        Double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Double arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ComputeCircleArea")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ComputeCircleArea", targetNamespace = "http://pservice.jyu.fi/", className = "fi.jyu.pservice.ComputeCircleArea")
    @ResponseWrapper(localName = "ComputeCircleAreaResponse", targetNamespace = "http://pservice.jyu.fi/", className = "fi.jyu.pservice.ComputeCircleAreaResponse")
    @Action(input = "http://pservice.jyu.fi/ComputeAreaImpl/ComputeCircleAreaRequest", output = "http://pservice.jyu.fi/ComputeAreaImpl/ComputeCircleAreaResponse")
    public String computeCircleArea(
        @WebParam(name = "arg0", targetNamespace = "")
        Double arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ComputeSquareArea")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ComputeSquareArea", targetNamespace = "http://pservice.jyu.fi/", className = "fi.jyu.pservice.ComputeSquareArea")
    @ResponseWrapper(localName = "ComputeSquareAreaResponse", targetNamespace = "http://pservice.jyu.fi/", className = "fi.jyu.pservice.ComputeSquareAreaResponse")
    @Action(input = "http://pservice.jyu.fi/ComputeAreaImpl/ComputeSquareAreaRequest", output = "http://pservice.jyu.fi/ComputeAreaImpl/ComputeSquareAreaResponse")
    public String computeSquareArea(
        @WebParam(name = "arg0", targetNamespace = "")
        Double arg0);

}
