
package net.webservicex.area;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AreaUnit", targetNamespace = "http://www.webserviceX.NET/", wsdlLocation = "http://www.webservicex.net/ConvertArea.asmx?WSDL")
public class AreaUnit
    extends Service
{

    private final static URL AREAUNIT_WSDL_LOCATION;
    private final static WebServiceException AREAUNIT_EXCEPTION;
    private final static QName AREAUNIT_QNAME = new QName("http://www.webserviceX.NET/", "AreaUnit");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://www.webservicex.net/ConvertArea.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AREAUNIT_WSDL_LOCATION = url;
        AREAUNIT_EXCEPTION = e;
    }

    public AreaUnit() {
        super(__getWsdlLocation(), AREAUNIT_QNAME);
    }

    public AreaUnit(WebServiceFeature... features) {
        super(__getWsdlLocation(), AREAUNIT_QNAME, features);
    }

    public AreaUnit(URL wsdlLocation) {
        super(wsdlLocation, AREAUNIT_QNAME);
    }

    public AreaUnit(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AREAUNIT_QNAME, features);
    }

    public AreaUnit(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AreaUnit(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AreaUnitSoap
     */
    @WebEndpoint(name = "AreaUnitSoap")
    public AreaUnitSoap getAreaUnitSoap() {
        return super.getPort(new QName("http://www.webserviceX.NET/", "AreaUnitSoap"), AreaUnitSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AreaUnitSoap
     */
    @WebEndpoint(name = "AreaUnitSoap")
    public AreaUnitSoap getAreaUnitSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.webserviceX.NET/", "AreaUnitSoap"), AreaUnitSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AREAUNIT_EXCEPTION!= null) {
            throw AREAUNIT_EXCEPTION;
        }
        return AREAUNIT_WSDL_LOCATION;
    }

}
